#include <iostream>
#include <iomanip>
#include <random>
#include <algorithm>
#include <cmath>

int main()
{
    std::random_device rd;  // Will be used to obtain a seed for the random number engine
    std::mt19937 gen(rd()); // Standard mersenne_twister_engine seeded with rd()
    std::uniform_real_distribution<float> dis(-1.0, 1.0);
    size_t N = 40*1000*1000;
    float * x = new float[N];
    for (int n = 0; n < N; ++n) {
        // Use dis to transform the random unsigned int generated by gen into a 
        // float in [1, 2). Each call to dis(gen) generates a new random float.
        x[n] = dis(gen);
    }
    // sort in absolute value
    std::sort(x,x+N,[](float a, float b) { return std::abs(a) < std::abs(b);});
    // print first and last 20
    // std::cout << std::hexfloat;
    for (int i=0; i<40; ++i) std::cout << x[i] << ' ';
    std::cout << '\n';
    for (int i=0; i<40; ++i) std::cout << x[N-1-i] << ' ';
    std::cout << '\n';
    std::cout << '\n';
    std::cout << std::hexfloat;
    for (int i=0; i<40; ++i) std::cout << x[i] << ' ';
    std::cout << '\n';
    for (int i=0; i<40; ++i) std::cout << x[N-1-i] << ' ';
    std::cout << '\n';

    delete [] x;
    return 0;
}

